version: 1
disable_existing_loggers: True

formatters:
  default:
    format: '%(asctime)s %(levelname)s - %(module)s:%(lineno)d (%(funcName)s) - %(message)s'
    datefmt: '%d-%b-%Y %H:%M:%S'

handlers:
  default:
    level: DEBUG
    class: logging.StreamHandler
    formatter: default

  spec:
    class: logging.FileHandler
    filename: all.log
    formatter: default

loggers:
  all:
    level: DEBUG
    handlers: [spec]

root:
  formatter: default
  handlers: [default]