version: 1
disable_existing_loggers: True

formatters:
  default:
    format: '%(asctime)s %(levelname)s - %(module)s:%(lineno)d (%(funcName)s) - %(message)s'
    datefmt: '%d-%b-%Y %H:%M:%S'

handlers:
  default:
    level: INFO
    class: logging.StreamHandler
    formatter: default

  all:
    level: INFO
    class: logging.FileHandler
    filename: logs/all.log
    formatter: default

  special:
    level: DEBUG
    class: logging.FileHandler
    filename: logs/all.log
    formatter: default
  
  telegram:
    level: ERROR
    class: config.CustomHTTPHandler
    formatter: default

loggers:
  special_debug:
    level: DEBUG
    handlers: [special]

  telegram:
    level: ERROR
    handlers: [telegram]

root:
  formatter: default
  handlers: [telegram, all, default]