EN:
  start: "Welcome to the *Plane_over_me_bot*. Provide your location via Telegram and
  get instant picture about nearest planes in the air. After getting the map with
  planes' marks you can examine the concrete plane by pushing the button with its
  parameters _(distance from you / plane model / plane altitude / plane speed)_.
  \n\nUse bot buttons, integrated to the keyboard:\n\n*Planes* - up to 5 planes around you,
  higher than 100 meters\n\n*Last location* - planes in you last provided location
  without sending new one (e.g. for requests from non-mobile Telegram)."
  map_caption: "{} planes on the map total in a 80 km circle: {}"
  no_ADS: ADS-B information about planes temporarily unavailable
  outdated: Data is outdated
  no_location: There is no last position in system. Please resend your location.
  plane_details: "({}) {} `({})`\n\n*{}* m / *{}* km/h
  \n_Distance from you: {} km_\n\n{}\n*>>>*\n{}\n\n_Photo credits: {}, {}, {} {}_"